---
- hosts: localhost
  connection: local
  become: yes
  vars_files:
    - defaults/main.yml

  tasks:
  - name: docker-compose
    template:
      src: docker-compose.yml.j2
      dest: /home/gorel/docker-compose.yml
      mode: 0700
      
