---
- hosts: localhost
  connection: local
  become: yes
  vars_files:
    - defaults/main.yml

  tasks:
  - name: docker-compose template
    template:
      src: docker-compose.yml.j2
      dest: /home/gorel/docker-compose.yml
      mode: 0700
    vars:
      some_list:
      - item1
      - item2
      - item3
