---
- hosts: localhost
  connection: local
  become: yes
  vars_files:
    - defaults/main.yml

  tasks:
  - name: docker-compose
    template:
      src: docker-compose.yml.j2
      dest: "{{ my_compose_path }}"
      mode: 0700
    
